name: PvP
version: 2.0.0
author: Smart , Rafael Auler
main: net.helix.pvp.HelixPvP
description: Plugin de kitpvp do KomboPvP
depend: [Core, DecentHolograms, PlaceholderAPI, ajLeaderboards]

commands:
   spawn:
   skit:
   youtuber:
   evento:
   tpall:
   sc:
   report:
   regras:
   req:
   site:
   loja:
   sudo:
   sealend123:
   lavainiciar:
   arenainiciar:
   shutdownserver:
   resetkdr:
   givekit:
   v:
   vanish:
   medalhas:
   medalha:
   consolesudo:
   requisitos:
   discord:
   sethologram:
   rank:
      aliases: [ranks]
   scoreboard:
      aliases: [score]
   verrank:
      aliases: [profile]
   sortearplayer:
      aliases: [sortear]   
   sorteio:
   actionbar:
   
   
   